### ISSUE TITLE
Correct usage of TransactionFilters

### ISSUE THREAD

**Issue by dylan-hoefsloot** [icco/lunchmoney#1]
Is this correct usage of TransactionFilters?
```golang
client.GetTransactions(ctx, &lunchmoney.TransactionFilters {
  StartDate: "2020-01-01",
  EndDate: "2020-12-01",
})
```
it raises an error saying `err: json: cannot unmarshal number into Go value of type string`

**Comment by icco** [comment]
Hi @dylan-hoefsloot, sorry I missed this. That should work.
